<a href="https://colab.research.google.com/github/Keshabh/AI-ML/blob/main/Day1_Data_Cleaning_Cheatsheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas • NumPy • Missing Values • Merging • Grouping • Encoding


In [43]:
#Importing Numpy and Pandas Library
import numpy as np
import pandas as pd

## Numpy Basics

In [44]:
#creating arrays
a = np.array([5,6,7])
b = np.array([[1,2,3.3], [4,5,6]])

#Array properties
print(a.shape, b.shape)
print(a.ndim, b.ndim)
print(a.dtype, b.dtype)


(3,) (2, 3)
1 2
int64 float64


In [45]:
#Helpful array creators
zeros_arr = np.zeros((3,2))
ones_arr = np.ones((4,4))
arange_arr = np.arange(1,100,15) #range of values between 1 and 100, with a step jump of 15
linspace_arr = np.linspace(0,9.7,20) #20 values in eqaul space between 1 and 10
print(zeros_arr, end='\n\n')
print(ones_arr,end='\n\n')
print(arange_arr,end='\n\n')
print(linspace_arr,end='\n\n')


[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[ 1 16 31 46 61 76 91]

[0.         0.51052632 1.02105263 1.53157895 2.04210526 2.55263158
 3.06315789 3.57368421 4.08421053 4.59473684 5.10526316 5.61578947
 6.12631579 6.63684211 7.14736842 7.65789474 8.16842105 8.67894737
 9.18947368 9.7       ]



In [46]:
#Basic statistics
print(np.mean(b))
print(np.min(b, axis=0)) #in each column, apply min
print(np.max(b, axis=1)) #in each row, apply max
print(np.std(b))

3.5500000000000003
[1.  2.  3.3]
[3.3 6. ]
1.6968107338965848


In [47]:
#Reshaping
c = np.arange(12)
print(c.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Pandas Basics

In [48]:
data = {
    "employee_id":[101,102,103,104,105],
    "age":[23,25,36,22,29],
    "gender":['Male','Female','Female','Male','Male'],
    "city":["Delhi", "Mumbai", "Kolkata", "Hyderabad", "Pune"]
}

df = pd.DataFrame(data)
df

employee_id  age  gender       city
0          101   23    Male      Delhi
1          102   25  Female     Mumbai
2          103   36  Female    Kolkata
3          104   22    Male  Hyderabad
4          105   29    Male       Pune

In [49]:
#Quick inspection
df.head(3) #if no param value provided, then by default returns first 5 rows

employee_id  age  gender     city
0          101   23    Male    Delhi
1          102   25  Female   Mumbai
2          103   36  Female  Kolkata

In [50]:
df.info() #each field properties like column name, number of non null in each column, data type of values inside that field, memory of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   employee_id  5 non-null      int64 
 1   age          5 non-null      int64 
 2   gender       5 non-null      object
 3   city         5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes


In [51]:
df.shape #dimension of dataframe

(5, 4)

In [52]:
df.columns #gives all the column names in the dataframe

Index(['employee_id', 'age', 'gender', 'city'], dtype='object')

In [53]:
df.describe() #gives statistical informations of numerical valued columns like min, max, mean, std, 1st quartile, 2nd quartile, 3rd quartile values.

employee_id        age
count     5.000000   5.000000
mean    103.000000  27.000000
std       1.581139   5.700877
min     101.000000  22.000000
25%     102.000000  23.000000
50%     103.000000  25.000000
75%     104.000000  29.000000
max     105.000000  36.000000

In [63]:
data_with_nan = {
    "employee_id":[101,102,103,104,105],
    "age":[23,25,36,None,29],
    "gender":['Male','Female','Female',None,'Male'],
    "city":[None, "Mumbai", "Kolkata", "Hyderabad", "Pune"]
}

#numeric values absence is populated with NaN i.e not a number
#string values absence is populated with None
df_with_nan = pd.DataFrame(data_with_nan)
df_with_nan

employee_id   age  gender       city
0          101  23.0    Male       None
1          102  25.0  Female     Mumbai
2          103  36.0  Female    Kolkata
3          104   NaN    None  Hyderabad
4          105  29.0    Male       Pune

In [64]:
#count missing value in each column
df_with_nan.isnull().sum()

employee_id    0
age            1
gender         1
city           1
dtype: int64

In [65]:
#Drop rows with missing values
df_with_nan.dropna()

employee_id   age  gender     city
1          102  25.0  Female   Mumbai
2          103  36.0  Female  Kolkata
4          105  29.0    Male     Pune

In [66]:
#Drop rows only if important field value is missing
df_with_nan.dropna(subset = ['age'])

employee_id   age  gender     city
0          101  23.0    Male     None
1          102  25.0  Female   Mumbai
2          103  36.0  Female  Kolkata
4          105  29.0    Male     Pune

In [68]:
#Fill numerical and categorical columns missing values
df_with_nan.fillna(0) #fills all missing values with 0

employee_id   age  gender       city
0          101  23.0    Male          0
1          102  25.0  Female     Mumbai
2          103  36.0  Female    Kolkata
3          104   0.0       0  Hyderabad
4          105  29.0    Male       Pune

In [73]:
df_with_nan['age'] = df_with_nan['age'].fillna(df_with_nan['age'].mean()) #fills missing values in numerical column with mean
df_with_nan['city'] = df_with_nan['city'].fillna("unknown")
df_with_nan['gender'] = df_with_nan['gender'].fillna(df_with_nan['gender'].mode()) #fills missing values in catgeorical column with mode
df_with_nan

employee_id    age  gender       city
0          101  23.00    Male    unknown
1          102  25.00  Female     Mumbai
2          103  36.00  Female    Kolkata
3          104  28.25     NaN  Hyderabad
4          105  29.00    Male       Pune

In [91]:
#Merging
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "city": ["Delhi", "Mumbai", "Delhi", "Bangalore"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 1, 3, 4],
    "amount": [250, 400, 150, 300, 500]
})

In [92]:
#Left join(how = left), Inner join(hwo = inner), Right join(how = right)
merged_data = pd.merge(customers, orders, on = 'customer_id', how='left')
merged_data

customer_id       city  order_id  amount
0            1      Delhi       101     250
1            1      Delhi       103     150
2            2     Mumbai       102     400
3            3      Delhi       104     300
4            4  Bangalore       105     500

In [80]:
#Group by
merged_data.groupby('city')['amount'].sum() #amount spent city wise

city
Bangalore    500
Delhi        700
Mumbai       400
Name: amount, dtype: int64

In [82]:
#Multiple aggregations
merged_data.groupby('city').agg({"amount":["sum", "min", "max"], "customer_id":"count"})

amount           customer_id
             sum  min  max       count
city                                  
Bangalore    500  500  500           1
Delhi        700  150  300           3
Mumbai       400  400  400           1

## Encoding(LabelEncoding, OneHotEncoding)

In [86]:
#Encoding (Machines dont understand text, we need to convert it into numbers)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

df_enc = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "city": ["Delhi", "Mumbai", "Delhi", "Bangalore"],
    "segment": ["Gold", "Silver", "Platinum", "Gold"]
})

label_encoder.fit_transform(df_enc['city']) #converts each unique values in the format of 0,1,2,3...
#values are alphabetically sorted and then numbers are assigned based on them
#sorted values = (bangalore, delhi, mumbai) = (0,1,2)

array([1, 2, 1, 0])

In [88]:
#one hot encoding
pd.get_dummies(df_enc, columns = ['city'], drop_first = True) #drop first removes first alphabetical column, caue it causes multi-collinearity
#mean, we can still retain the same information by removing city_banagalore column, cause if both column city_delhi and city_mumbai has False
#then, by default it means city_bangalore in that specific record would be True

customer_id   segment  city_Delhi  city_Mumbai
0            1      Gold        True        False
1            2    Silver       False         True
2            3  Platinum        True        False
3            4      Gold       False        False

## Imp Notes

1.When should you use median instead of mean?

If the column has outliers → use median.

Ex: 10,20,30,10000 (data is skewed here as 10000 is a outlier, if a mean is taken, mean value will be skewed more towards 10000)
  
If the column is normal → use mean.

2.Label Encoding vs One-Hot Encoding?

Label Encoding if categorical values are ordered and the same order needs to be preserved when encoded, else One Hot Encoding.

Ex: Small < Medium < Large can be 0,1,2

But if Male, Female, then order is not important, and then we can use One Hot Encoding.

In case, if we have Male, Female as 0,1, it gives model a false info where it thinks Female has 1 unit more value than Male.
But practically one values like small, medium, large, if it understands it, then its not an issue, cause it indeed is a fact where small < medium < large, and can be represented as 0,1,2.

3.Can we combine arrays of size 2×2, 3×2, and 4×2 inside one ndarray?

No, cause numpy requires all array to be of same shape, inside one ndarray.

4.What does a shape like (4, 2, 2) or (3, 2, 2) mean?

4 matrix, each of size 2,2.

5.Are there any methods to work with string arrays in NumPy?

In [107]:
#since numpy works with fixed size data, then it picks up max length value, and trims the rest, if in further operations any text size exceeds that.
#Max size : Chennai is of 7 length
#so, later if we try to do Delhi to New Delhi, it is to be trimmed to New Del only
arr = np.array(["Delhi", "Mumbai", "Chennai"])

arr = np.char.replace(arr, "Delhi", "New Delhi")
arr = np.char.lower(arr)

print(arr)

['new del' 'mumbai' 'chennai']


6.fit_transform() means.

Fits i.e Learns(some imp informations such as min,max,mean,median,..) and Transforms(applies based on what it has learned) i.e performs the operations in a single step.